### PR TITLE
ContactUs Page Enhanced

### LINKED ISSUE #199: [UI]Improvement in Contact Us PAge
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

### PR DESCRIPTION
**Pull request by Bhum-ika**
## 📋 Description
Improved styling of the contactUs PAge

## 🔨 Changes Made

Changes are made in the UI

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #199 

## 📸 Screenshots (if applicable)
Screenshot 2024-10-22 174622

Screenshot 2024-10-22 174558

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@Bhum-ika 

This UI is too good but it is totally different from the Current Website UI

**Comment by Bhum-ika** [comment]
@MitulSonagara 
To match the ui, I kept some elements red, if u still think it doesn't align, dw, I will work on it

I'll make sure you like the final output

**Comment by Bhum-ika** [comment]
Screenshot 2024-10-22 195659
image
 Which one do you like
@MitulSonagara

**Comment by MitulSonagara** [comment]
@Bhum-ika 

can you make it simple like this 
image

**Comment by Bhum-ika** [comment]
Okay

**Comment by Bhum-ika** [comment]
Option-1 for lightScreenshot 2024-10-23 162855
Btw this looks dull
Option-2 for lightScreenshot 2024-10-23 162928
Option-1 for darkScreenshot 2024-10-23 163014
Option-2 for darkimage

@MitulSonagara Kindly see and let me know which one you want

**Comment by Bhum-ika** [comment]
@MitulSonagara Please reply

**Comment by MitulSonagara** [comment]
Option 2 for dark mode...

for light mode both will be done

**Comment by Bhum-ika** [comment]
Pushed the changes

**Pull request merged**
