### PR TITLE
Add New line feature and fix input field clear on send message

### LINKED ISSUE #235: New line and clear message field after messge is sent

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #235

https://github.com/user-attachments/assets/47b5ebc1-eb7d-4992-bd84-9403d8b856a2

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Hi @MitulSonagara these are some minor changes so please reduce the labels to `level 1`

also please add me as a collaborator in your repo, we're reviewing the contributors and reducing the labels

thank you - program manager

**Comment by shubhagarwal1** [comment]
> Hi @MitulSonagara these are some minor changes so please reduce the labels to `level 1`
> 
> also please add me as a collaborator in your repo, we're reviewing the contributors and reducing the labels
> 
> thank you - program manager

**Comment by shubhagarwal1** [comment]
> Hi @MitulSonagara these are some minor changes so please reduce the labels to `level 1`
> 
> also please add me as a collaborator in your repo, we're reviewing the contributors and reducing the labels
> 
> thank you - program manager

Hey @MastanSayyad fixing multiple things in one PR, as you stated me last time so i followed this, than what is diffrence in adding some lines to documentation and improving the exisign features please guide me.

**Comment by MastanSayyad** [comment]
@shubhagarwal1 changes are less it cannot have level 2, there are some contributors who adds features and some logic and they too get level 2 which will be not fair with these kind of PRs

It will still have level 1, you are top contributor who may get rewards so we have to be litlle harsh on top 10

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 changes are less it cannot have level 2, there are some contributors who adds features and some logic and they too get level 2 which will be not fair with these kind of PRs
> 
> It will still have level 1, you are top contributor who may get rewards so we have to be litlle harsh on top 10

I understand.

**Comment by MitulSonagara** [comment]
@MastanSayyad 

I added as collaborator in my repo....
and thanks for review this is my first time as project admin and i already has one of the mentor as collaborator but no suggestions to me from them

**Pull request merged**
