### PR TITLE
Added Animated Footer And Social Media Icons

### LINKED ISSUE #89: [FEATURE]: Adding Animated Footer to the Website
**Description**
The current website lacks footer part and social media icons to reach out to the particular admin of the website. Changing the footer into better looking and responsive features.

**Describe the solution you'd like**
> Footer Component: Move the text "Made with ❤️ by Mitul Sonagara © 2024" from the current location to a dedicated footer component.
>Adding social media icons ( Linkedin, Github, Instagram,......) with animation effect when someone hover on it . 
>The footer part helps user to reach out the website admin if user finds any problem or bug in the website.

**Screenshots**
Screenshot 2024-10-14 114410

### PR DESCRIPTION
**Pull request by GyanaPrakashSahoo7853**
## 📋 Description

Added animated waves to the footer part with animated social media icons.

## 🔨 Changes Made

 Fixes #89 

- Added animated footer with waves 
- Added animated social media icons 
- Added "Made with ❤️ by Mitul Sonagara © 2024"

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] New feature (non-breaking change which adds functionality) ✨

## 📸 Screenshots 

https://github.com/user-attachments/assets/0de245d4-8682-4dcc-9760-35879920610a

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by GyanaPrakashSahoo7853** [comment]
By mistakenly i added two commit can you please Delete the ''AddedAnimatedFooterDesign'' commit

**Comment by GyanaPrakashSahoo7853** [comment]
I am deleting this because by mistakenly i have not added the code folder inside the public folder as you mentioned earlier and pushed it  so i want to delete the files that i have not added inside the public folder .

But the AddedFooter branch is inside the public folder as you mentioned earlier. Please review the AddedFooter branch changes .

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

I can not seeing any changes in this branch... if any other branches is there then you need to close this PR and raise new PR.

I will suggest you that if any confusion is there then create a new branch .... make all changes on that and raise new PR

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853
> 
> I can not seeing any changes in this branch... if any other branches is there then you need to close this PR and raise new PR.
> 
> I will suggest you that if any confusion is there then create a new branch .... make all changes on that and raise new PR

Should i close this pull request completely and raise another one

**Pull request closed without merging**
