### PR TITLE
Refactor: code quality and react-query

### LINKED ISSUE #122: [BUG] Code quality improvement remove staled code
**Describe the bug**
Some points that can improve overall project

1. remove all staled code and functions
2. remove duplicate code make it simple
3. add `react-query` instead of traditional `useEffect`
4. revamp API routes with best practices.

### PR DESCRIPTION
**Pull request by PriyanshuPz**
## 📋 Description
 improve overall project

## 🔨 Changes Made

1. remove all staled code and functions
2. remove duplicate code make it simple
3. add `react-query` instead of traditional `useEffect`
4. revamp API routes with best practices.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #122 

## 📸 Screenshots (if applicable)
image

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

image

**Comment by PriyanshuPz** [comment]
@MitulSonagara I have checked by building

**Comment by MitulSonagara** [comment]
image

**Comment by MitulSonagara** [comment]
image

these are server logs

**Comment by PriyanshuPz** [comment]
@MitulSonagara That was the error in a hook checking for encryption key. I have fixed

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

what is this issue
image

whenever i tried to create encryption key it is giving me this pop up

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

image

this loader is loading continuously

**Comment by PriyanshuPz** [comment]
It is not related to this PR.
As generation of encryption key takes time according to user's device

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

image

loader position changed... and taking too much time to load

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

changed the dark mode logo for this navbar
image

**Comment by PriyanshuPz** [comment]
@MitulSonagara I didn't changed any UI. Let me investigate issues and fix

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

I am merging this ... you can raise new issues for what i comented

**Pull request merged**
