### PR TITLE
Feat: created issue/pr template

### LINKED ISSUE #7: Issue Templates for this project
Anyone who can make better issue Template for this project can comment on this.

### PR DESCRIPTION
**Pull request by harish08102004**
**Description**
This PR adds issue and pull request (PR) templates to the repository. These templates are designed to streamline the process for reporting bugs, requesting features, and submitting PRs by providing a consistent structure for contributors to follow.

**Issue Templates**:
Bug report template
Feature request template
Pull Request Template:
Standardized format for PRs to ensure all necessary information is included and follows project guidelines.

**Related Issue**
Closes #7

### CODE REVIEW

**Comment by harish08102004** [comment]
@MitulSonagara Can you please authorize it

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
@harish08102004 

can you also make PR template?
If you can i will make this PR as level 2

**Comment by harish08102004** [comment]
@MitulSonagara sure I can work on it.
Do I need to create a separate PR ?

**Comment by MitulSonagara** [comment]
@harish08102004 ya you can made it separate PR i will label that level 1.

**Comment by harish08102004** [comment]
Hey @MitulSonagara I can made change in this PR itself can you make this as level 2?

**Comment by MitulSonagara** [comment]
@harish08102004 ya you can do it

**Comment by harish08102004** [comment]
Hey @MitulSonagara even if make changes in the same branch and push it, it's creating a new PR what should I do ?

**Comment by MitulSonagara** [comment]
@harish08102004 Ok bro leave it I will make the PR template ... coz i need some workflows as well

You can work on something else

**Comment by harish08102004** [comment]
Hey but I already made the PR can you review it and merge it.

**Pull request merged**
