### PR TITLE
add about page

### LINKED ISSUE #61: ADD: About page to the website
I propose to add a about us page on the websit eso that, we can enhae the website informative and more contributing to the solution.

### PR DESCRIPTION
**Pull request by shubhagarwal1**
Fixes #61  
Screenshot 2024-10-16 at 2 32 18 AM

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

image

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1
> 
> image

okay looking into the problem

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

have you solved the errors??

**Comment by shubhagarwal1** [comment]
hey @MitulSonagara  i have solved conflicts for this branch.

**Comment by MitulSonagara** [comment]
image
@shubhagarwal1

**Pull request closed without merging**
