### PR TITLE
add toaster on login page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
> ## 📋 Description
> ## 🔨 Changes Made
> 
> ## ✅ Checklist
> Before submitting the PR, please make sure you have completed the following:
> 
> * [ ]  My code follows the style guidelines of this project.
> * [ ]  I have performed a self-review of my own code.
> * [ ]  I have commented my code, particularly in hard-to-understand areas.
> * [ ]  I have made corresponding changes to the documentation (if applicable).
> * [ ]  My changes generate no new warnings.
> * [ ]  I have tested it locally and it works fine.
> * [ ]  Any dependent changes have been merged and published in downstream modules.
> 
> ## 🏷️ Types of Changes
> What type of changes does your code introduce? (Check all that apply)
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue) 🐛
> * [ ]  New feature (non-breaking change which adds functionality) ✨
> * [ ]  UI enhancement (non-breaking change which enhances UI) 🎨
> * [ ]  Documentation update 📚
> 
> ## 🤝 Related Issues
> * Fixes #
> 
> ## 📸 Screenshots (if applicable)
> _Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!_

Bro isme se thodi details fill kar dena coz pull request pe review hota h

**Review by MastanSayyad — COMMENTED** [review]
Hi @MitulSonagara code formatter have been used in some places therefore add `level1` here

image

**Comment by shubhagarwal1** [comment]
> Hi @MitulSonagara code formatter have been used in some places therefore add `level1` here
> 
> image

hey @MastanSayyad adding new functionlaity is to be added as level 2 as you prev. told me, also code formatter is part of the process in order to make code more readable

**Comment by MastanSayyad** [comment]
Nope if the functionality is been added with lesser changes then it should be level 1, i checked the code for toaster, rest of the code is formatted

**Comment by shubhagarwal1** [comment]
> Nope if the functionality is been added with lesser changes then it should be level 1, i checked the code for toaster, rest of the code is formatted

I understand .

**Pull request merged**
