### PR TITLE
Added feedback   solved #129

### PR DESCRIPTION
**Pull request by KapuluruBhuvaneswariVspdbct**
## 📋 Description

Added feedback   solved #129
## 🔨 Changes Made

Added feedback   solved #129
- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
image

@KapuluruBhuvaneswariVspdbct

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
solved issues

**Review by KapuluruBhuvaneswariVspdbct — COMMENTED** [review]
solved issues

**Comment by MitulSonagara** [comment]
@KapuluruBhuvaneswariVspdbct 

there is no navigation for accessing the feedback page and this is same as the contact us page so i am closing this issue and PR

**Pull request closed without merging**
