### PR TITLE
Add loading state to the change button

### LINKED ISSUE #102: [BUG]Handle debounce on edit user name (loader)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #102 
## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

bro when i click to edit username button its nothing heppening

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1
> 
> bro when i click to edit username button its nothing heppening

can we connect over discord 
i have issue i just stucked ont the sign in can we plese connect over discord, not abel to send the vericationemail 
@MitulSonagara that is why this issue rasied was not abel to test

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

sure lets connect

**Comment by MitulSonagara** [comment]
image

**Pull request closed without merging**
