### PR TITLE
Add git contributros page

### LINKED ISSUE #107: ADD GIT CONTRIBUTOR PAGE TO THE WEBSITE

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #107
Screenshot 2024-10-16 at 1 57 06 AM

### CODE REVIEW

**Comment by MitulSonagara** [comment]
resolve the conflicts 
@shubhagarwal1

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

bro you have to solve conflicts for the navbar... as it has different navbar after login and before login

**Comment by shubhagarwal1** [comment]
hey @MitulSonagara i have solved the conflicts

**Comment by MitulSonagara** [comment]
image

@shubhagarwal1

**Comment by MitulSonagara** [comment]
image

**Pull request merged**
