### PR TITLE
Added css property to scroll in modal

### LINKED ISSUE #125: [BUG] Not able to scroll down in Encryption pop-up window
**Describe the bug**
Not able to scroll down in Encryption pop-up window

**To Reproduce**
1. Go to Encryption 
2. Click on Encryption 

**Expected behavior**

**Screenshots**
o2
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
## 📋 Description

Added css property to scroll in modal

## 🔨 Changes Made

Added css property to scroll in modal

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues
- Fixes #125

## 📸 Screenshots (if applicable)

Animation4
---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by hemanthkumar-21** [comment]
@MitulSonagara  level1 is needed for this not level2 @MastanSayyad

**Comment by hemanthkumar-21** [comment]
@mehul-m-prajapati  we had reviewed all your prs all are good. but few prs need to be downgrade. I hope you understand. all the best for your contributions

**Review by MastanSayyad — COMMENTED** [review]
Minor css change, so no levels

**Comment by mehul-m-prajapati** [comment]
@Hemu21 ; no worries. Levels are assigned according to understanding of PAs. I only focus on given tasks,
Thanks

**Pull request merged**
