### PR TITLE
fix #38 username validation on signup page

### LINKED ISSUE #38: Bug: Validation Error on Register page does not go even after user changes it.
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a user is entering his/her username on register form, and if the username is already taken we get a validation error in red text below it. But if the user changes its user name, the validation error must also change after validating the new username

### Steps to Reproduce

1. Go to signup page
2. Type a username that's already taken and get the validation error.
3. change the username to something unique.
4. Validation error still doesn't go.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

When a user is entering his/her username on register form, and if the username is already taken we get a validation error in red text below it. But if the user changes its user name, the validation error must also change after validating the new username

### Expected Results

if the user changes its user name, the validation error must also change after validating the new username

### Technical details

https://github.com/user-attachments/assets/1aa13f17-0c46-4734-af64-45fd04885470

### PR DESCRIPTION
**Pull request by ZayedShahcode**
fixes issue #38.
It was just a simple status code error.
Now even after adding a invalid username and later fixing it changes the validation message.

https://github.com/user-attachments/assets/f2bf9196-da10-4049-9a3e-e6f999e3a32d

### CODE REVIEW

**Comment by ZayedShahcode** [comment]
Please add gssoc and hacktoberfest tags.

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
@ZayedShahcode 

There is still one problem,,, if any username already exist and i use that then the error text is showing permanently.

Please fix that.

**Comment by ZayedShahcode** [comment]
@MitulSonagara fixed it. Btw should I  improve the validation for password as to include atleast one special character and one capital letter.

**Comment by MitulSonagara** [comment]
@ZayedShahcode 

Nice work brother.

**Pull request merged**
