### PR TITLE
Add contact us page

### LINKED ISSUE #146: ADD contact us page

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #146 
Screenshot 2024-10-19 at 3 31 46 AM

### CODE REVIEW

**Comment by MitulSonagara** [comment]
image

@shubhagarwal1

**Comment by shubhagarwal1** [comment]
> image
> 
> @shubhagarwal1

can we connect @MitulSonagara

**Comment by MitulSonagara** [comment]
image

**Comment by MitulSonagara** [comment]
image

**Pull request merged**
