### PR TITLE
fix: auto generate encryption keys if user do not have

### LINKED ISSUE #181: [BUG] On Login create encryption key if user doesn't have that
- Currently user explicitly needs to generate encryption key but automate that when user login.

### PR DESCRIPTION
**Pull request by PriyanshuPz**
## 📋 Description
adds logic to auto generate encryption key if user doesn't have.

## 🔨 Changes Made

- adds logic to auto generate encryption key if user doesn't have.
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #181 

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
image

Messages are not decrypting....

**Comment by PriyanshuPz** [comment]
@MitulSonagara It generates private key if user doesn't have it doesn't affect when you already created keys

**Comment by PriyanshuPz** [comment]
@MitulSonagara I am search solution to sync keys also. I will raise issue and fix that when I get suitable solution soon

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Ya find some solution coz creating new encryption key is causing the deletation of messages and adding the encryption key again and again is not so good...

**Comment by PriyanshuPz** [comment]
@MitulSonagara Please Review this PR and merge

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 
image

**Comment by PriyanshuPz** [comment]
@MitulSonagara Please check again

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

If it will generate new key automatically then old messages get deleted?

**Review by MitulSonagara — APPROVED** [review]

**Pull request merged**
