### PR TITLE
enhanced default scroll bar

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@MitulSonagara 
I have enhanced the default scroll bar and removed the black border too
Kindly check it out

https://github.com/user-attachments/assets/e97b51f6-a122-4666-b648-ae767c3bedf7

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

Please follow the PR template while creating the PR

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

Use the colors from the UI for light mode and dark mode coz this is looking as similar as default one

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
I tried it, but i couldn't do it

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Check now 
Now i have made it to look for both dark and light modes, and also i removed the black line too
from this to this


https://github.com/user-attachments/assets/1613e67f-b550-44bc-91fe-5f8d4ba29975


to this


https://github.com/user-attachments/assets/0e4966f1-c291-4e0c-8029-da1e84c25e1c

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

Please mention the issue to automatically close it

**Pull request merged**
