### PR TITLE
Added debounce query in search bar

### LINKED ISSUE #176: [FEATURE] Add Debounce to Search Bar
**Is your feature request related to a problem? Please describe.**
when typing in the search bar causes multiple rapid requests to the server. This leads to slow response times and can overwhelm the backend, resulting in delays and potential crashes.

**Describe the solution you'd like**
I would like to implement a debounce feature for the search bar that delays the execution of the search function until the user has stopped typing for a specified duration (e.g., 300 milliseconds). This will ensure that only the final input after the user has finished typing triggers a search request.

**Describe alternatives you've considered**
na

**Additional context**
no

---
t1

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
## 📋 Description

Added debounce query in search

## 🔨 Changes Made
- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #176 

## 📸 Screenshots (if applicable)

Capture
---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by mehul-m-prajapati** [comment]
**NOTE** : There is a bug in the search function. It is not fetching registered users  (#206)

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

can you fix the problem of message decryption?... there is a problem in which message is not getting decrypted if you want you can change the schema and change the encryption decryption method also

**Comment by mehul-m-prajapati** [comment]
@MitulSonagara : Already raised issue #178.
I will fix it today

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

Sure coz i am having this issue
image

**Pull request merged**
