### PR TITLE
Enhanced the ui of terms and condition page

### LINKED ISSUE #231: [UI]Term and condition page enhancement
image

as you can see it not looking good i can enhance its UI to look even more better

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue title :  Term and condition page enhancement
 issue #231 

Screenshot 2024-10-28 111914

Screenshot 2024-10-28 111943

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ X] My code follows the style guidelines of this project.
- [X ] I have performed a self-review of my own code.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have made corresponding changes to the documentation (if applicable).
- [X ] My changes generate no new warnings.
- [X ] I have tested it locally and it works fine.
- [X ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ X] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #231  

 

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
when i click on terms and condition link this gives me this 
image


and these are server logs
image

**Comment by MitulSonagara** [comment]
image

**Comment by Sawan-Kushwah** [comment]
@MitulSonagara 

https://github.com/user-attachments/assets/c2c2f610-8584-4584-b93c-6c254dae6749

Check it our once , resolved all issue !!

let me know if again its creating some issue ?

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
image
'

**Pull request closed without merging**
