### PR TITLE
feat: Settings to change username of the user

### LINKED ISSUE #71: [FEATURE] Settings to change username of the user
**Is your feature request related to a problem? Please describe.**
User should be able to change their username. as username on Google Auth is not decided by user. it is fetched from email

**Describe the solution you'd like**
A form to submit username

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by PriyanshuPz**
## 📋 Description
Feature to change username

## 🔨 Changes Made

- A new form to change username
- Session optimized
- zustand added for modal pops

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [x] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #71

## 📸 Screenshots (if applicable)

image

image

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Upstream the branch and solve the conflicts

**Comment by PriyanshuPz** [comment]
@MitulSonagara solved

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

if any user will change their username then they will be able to login using that username also??

**Comment by PriyanshuPz** [comment]
@MitulSonagara user can login with updated username only

**Pull request merged**
