### PR TITLE
Add the navbar to the enhancement, made it sleek and add responsiveness to it 

### PR DESCRIPTION
**Pull request by shubhagarwal1**
## 🔨 Changes Made

- 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ] My changes generate no new warnings.
- [ ] I have tested it locally and it works fine.
- [ ] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [ ] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [ ] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
hi @MitulSonagara code formatted and the chnages are minor so remove all `labels` i.e. no label to PR

image

original changes:

image

**Comment by shubhagarwal1** [comment]
> hi @MitulSonagara code formatted and the chnages are minor so remove all `labels` i.e. no label to PR
> 
> image
> 
> original changes:
> 
> image

Have made the navbar responsive the as previously mentioned i code formatter is the part of the process.

**Comment by MastanSayyad** [comment]
@shubhagarwal1 I have reviewed the code line by line so this should have `level1` @MitulSonagara 
also stop using code formatted it will mix the actual changes with no changes which is hard to review as said top 10 review is going to be harsh

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 I have reviewed the code line by line so this should have `level1` @MitulSonagara also stop using code formatted it will mix the actual changes with no changes which is hard to review as said top 10 review is going to be harsh

i understand

**Comment by MitulSonagara** [comment]
@MastanSayyad 



> @shubhagarwal1 I have reviewed the code line by line so this should have `level1` @MitulSonagara also stop using code formatted it will mix the actual changes with no changes which is hard to review as said top 10 review is going to be harsh

I will take care of this

**Comment by shubhagarwal1** [comment]
Hey @MastanSayyad as decided there should be level 1 but not levels, why

**Comment by MitulSonagara** [comment]
@shubhagarwal1 
@MastanSayyad 

Sorry it was my mistake i just missed the thing of level 1

> Hey @MastanSayyad as decided there should be level 1 but not levels, why

**Pull request merged**
