### PR TITLE
enhanced the contact us page

### PR DESCRIPTION
**Pull request by AswaniBolisetti**
@MitulSonagara 
I have enhanced the contact page
Kindly check now
please consider it as level3 i have made it responsive too

I have changed the ui
from this 

oldcontact

to this

https://github.com/user-attachments/assets/0e9d1cca-b8ea-4237-a61f-6f596e800314

### CODE REVIEW

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Please consider it as level3, i have added the responsiveness too

issue no : #268 

https://github.com/user-attachments/assets/f739f205-11e5-46c5-901e-13ef9963c795

**Comment by MitulSonagara** [comment]
Solve this error

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Please check now
Solved the issue

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

drop down menu is not visible in dark mode and also reduce the upper margin of the form in desktop mode
image

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Please check now 
I have done the changes 


https://github.com/user-attachments/assets/99ff4df2-166a-4c19-9a14-4d82ba81bf3d

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Please consider it as level3

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Please merge this

**Comment by AswaniBolisetti** [comment]
@MitulSonagara please merge this

**Pull request merged**
