### PR TITLE
Fixed mid content div in main page.

### PR DESCRIPTION
**Pull request by aryadevesh**
## 📋 Description

I changed the given padding to the main section of 12 rem which caused the content in-between to shrink. Check the issue in below ss :- 
image

## 🔨 Fixed issue #124 

- removed padding the main section of page.tsx.
- Reduced size of text a little-bit
- The UI of the whole website does not follow standards in responsiveness so chosen the best possible solution.

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

image

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@aryadevesh you have decrease the height of main content

Now
image

Original
image

**Comment by aryadevesh** [comment]
Increased the height of the div.


image

if we try to increase even more height than this then this might affect the responsiveness in the mobile view due to the structure of the Front-end written.

Current solution is Not conflicting with the main issue resolved.
image

**Comment by MitulSonagara** [comment]
@aryadevesh 

The main page is changed ... so if you want to work on this issue then you have to solve the conflicts.... or you can raise new issue

**Comment by aryadevesh** [comment]
I will raise new issue with the updated code. Resolving the conflicts will take more time.

**Comment by MitulSonagara** [comment]
@aryadevesh 

Okay no probelm

**Pull request closed without merging**
