### PR TITLE
feat: Secret Passphrase for unlocking keys.

### LINKED ISSUE #232: [FEATURE] Encryption key long asking fix
**Is your feature request related to a problem? Please describe.**
Add a Secret Passphrase for unlocking keys. It is easy to keep in mind instead of adding full encryption key.

**Describe the solution you'd like**
Ask for adding a Secret Passphrase like this
image

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by PriyanshuPz**
## 🔨 Changes Made

- fixes #232 
- 
- 

## ✅ Checklist

Before submitting the PR, please make sure you have completed the following:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes generate no new warnings.
- [x] I have tested it locally and it works fine.
- [x] Any dependent changes have been merged and published in downstream modules.

## 🏷️ Types of Changes

What type of changes does your code introduce? (Check all that apply)

- [x] Bug fix (non-breaking change which fixes an issue) 🐛
- [ ] New feature (non-breaking change which adds functionality) ✨
- [x] UI enhancement (non-breaking change which enhances UI) 🎨
- [ ] Documentation update 📚

## 🤝 Related Issues

- Fixes #232

## 📸 Screenshots (if applicable)

---

*Thank you for contributing to Truth-Tunnel! We look forward to reviewing your PR and getting it merged!*

### CODE REVIEW

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 
image

**Comment by PriyanshuPz** [comment]
@MitulSonagara Please review again

**Comment by PriyanshuPz** [comment]
@MitulSonagara conflict fixed

**Comment by PriyanshuPz** [comment]
@MitulSonagara I recommend to merge #184 first

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

I have merged your Auto encryption key PR thats why there is another conflicts... you want to solve it or i revert that PR

**Comment by PriyanshuPz** [comment]
@MitulSonagara I have fixed conflicts.

Let me let you why messages deletes when `encryptedPrivateKey` changes.

1. In current architecture we are encrypting messages with encryption key and saving that key in db with a secret passphrase encryption 
  - `messages` encrypted by `encryption key`
  - `encryption key` encrypt by `secret passphrase`
  - At the end of the day user needs to remember a user friendly secret passphrase only.

2. We delete previous messages when change `encryption key` because user will change `encryption key` if they forget the passphrase. And according to architecture we can decrypt messages with `encryption key` if we don't have that then messages cannot be read. 

3. See `encryption key` in our db is encrypted by a passphrase if user forgets that then we cannot retrieve`encryption key` and hence cannot decrypt messages.

4. In case you want to migrate old messages to new `encryption key` then you need the passphrase as we can decrypt previous messages from `old encryption key` and encrypt them with new. But for that we need secret passphrase. And it makes no sense why user change `encryption key` if they know previous one.

5. If you want **(NOT RECOMMENDED)** to keep previous messages even without previous secret passphrase then we need to store `encryption key` in our db without any encryption or secret passphrase. And user don't even need to do anything as if we are using everything on server then first it is not encryption and second the motto of the project will break.

Let me know what you thinking.
Will solve accounting or you can merge the PR as it ia a accurate recommended architecture.

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Ok i got it... but i have one question... is user need to change encryption key in every 7 day or it will last for life long

**Comment by MitulSonagara** [comment]
image

**Comment by PriyanshuPz** [comment]
No @MitulSonagara No changing of encryption key

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Ok so if i create one new account today and create passphrase then for how long i can remember passphrase for that time i can access my messages

**Comment by PriyanshuPz** [comment]
@MitulSonagara until you change it

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

OK done bro all doubts clear ... nice work

**Comment by MitulSonagara** [comment]
image

**Comment by PriyanshuPz** [comment]
@MitulSonagara Tested and fixed

**Comment by MitulSonagara** [comment]
image

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

try to run 

npm run build

**Comment by PriyanshuPz** [comment]
Ya I did two times 
Please again
@MitulSonagara

**Comment by MitulSonagara** [comment]
https://github.com/user-attachments/assets/ea32f6e5-ee2a-49cc-a669-85d38e0e1182

when i sign in this is showing me that please log in

**Comment by PriyanshuPz** [comment]
@MitulSonagara I think that is not related to this PR
let me check

**Comment by MitulSonagara** [comment]
coz currently deployed website is working perfectly
image

**Comment by PriyanshuPz** [comment]
https://screenrec.com/share/LtF4kuBH2y
@MitulSonagara check it is working

**Comment by PriyanshuPz** [comment]
@MitulSonagara fixed longer loading in video when message decrypt

**Comment by PriyanshuPz** [comment]
Please check again by making a fresh account @MitulSonagara

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Okay brother it is working perfectly after creating new account. 

But there is a bug like after sign up. it asked me to generate my passphrase. but then i send message to me it showed me this
image

And it fixed by adding my passphrase in change key section. but after logout and then login still i have to add to passphrase in change key section. 

So my concern is if it is neccesary to add key all the time then there should be pop up for adding passphrase whenever i login.

and also it is showing me wrong timing of the message as in 5 hours

**Comment by PriyanshuPz** [comment]
@MitulSonagara I sent a recording to you where everything was seamless. My suggestion is to merge this PR. 
And if their is any error then will fix after creating a urgent issue

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Sure i am merging this ... just resolve this conflict

**Review by MitulSonagara — APPROVED** [review]

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

as your video i have to refresh the page every time i receive new message so fix that bug in new issue... BTW nice work

**Comment by PriyanshuPz** [comment]
> @MitulSonagara fixed longer loading in video when message decrypt

Fixed here. Will check again tomorrow @MitulSonagara

**Pull request merged**
