### PR TITLE
Modified README.md file & Created LICENSE File for project

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved:

- Issue #56 

### 1) Incomplete animated line separators and added GSSoC 2024 Extended & Hacktoberfest accepted banners
There are sections in the README.md file where the line separators are missing! I want to fill those gaps and also add the GSSoC 2024 Extended & Hacktoberfest accepted image so that contributors know that this repository is officially accepted for GSSoC contribution.

### 2) Replace the Contact section  with a **Team section**
The Contact section in the **README.md** file was not looking attractive and has been replaced with the Team section.

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors. I would like to update it and try to automate the process.

## 2. Addition of a LICENSE File to the project
The presence of a LICENSE file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a LICENSE file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.

# Reference Video:

https://github.com/user-attachments/assets/2ba437d4-c695-4b0d-b262-924367221f6b

### CODE REVIEW

**Review by MitulSonagara — APPROVED** [review]

**Comment by rajdeepchakraborty-rc** [comment]
@MitulSonagara Thanks a lot for reviewing the PR. Please do assign the PR to me.

**Comment by rajdeepchakraborty-rc** [comment]
Thanks a lot! Hope you have a great day ahead 😄

**Comment by MitulSonagara** [comment]
@rajdeepchakraborty-rc 
Assign is not needed for the points but still i am assigning to you

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Assign is not needed for the points but still i am assigning to you

@MitulSonagara I had not been assigned in a PR earlier and had opened a discussion about it and the Admins asked me to let the Project admins know to assign the PR and Issues. That's why I informed you to avoid raising any problems from your end further.

**Pull request merged**
